name: Run Build
env:
  UPLOAD_TOKEN: 'dummyToken'
on:
  workflow_dispatch:
    inputs:
      customFileName:
        description: 'Enter a custome name for the built APK'
        type: string
        default: 'TestApp'

      majorRelease:
        description: 'Is this a major release?'
        type: boolean
        default: false
      

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make file executable
        run:  chmod +x build.sh upload.sh
        
      # CLI call to simulated build process
      - name: Run Build
        run: |
          ./build.sh --platform Android --project-name "${{github.event.inputs.customFileName}}"

      # CLI call to simulated upload process
      - name: Version tagging
        if: github.ref == 'refs/heads/main'
        uses: anothrNick/github-tag-action@1.67.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          INCREMENT: ${{ github.event.inputs.majorRelease == 'true' && 'major' || 'minor' }}
          
      - name: Rename APK and upload
        if: github.ref == 'refs/heads/main'
        run: |
          APK_PATH="build/Android/${{ github.event.inputs.customFileName }}.apk"
          mv "$APK_PATH" "build/Android/${{ github.event.inputs.customFileName }}-${{ steps.auto_version.outputs.new_tag }}.apk"
    
          for file in build/Android/*; do
            ./upload.sh android "$file"
          done
