name: Run Build
env:
  UPLOAD_TOKEN: 'dummyToken'
on:
  workflow_dispatch:
    inputs:
      customFileName:
        description: 'Enter a custome name for the built APK'
        type: string
        default: 'TestApp'
      

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make file executable
        run:  chmod +x build.sh upload.sh
        
      # CLI call to simulated build process
      - name: Run Build
        run: |
          ./build.sh --platform Android --project-name "${{github.event.inputs.customFileName}}"

      # CLI call to simulated upload process
      - name: Upload
        if: github.refs == 'refs/heads/master'
        run: |
          for file in build/Android/*; do
            ./upload.sh android "$file"
          done
