name: Run Build
env:
  UPLOAD_TOKEN: 'dummyToken'
on:
  workflow_dispatch:
    inputs:
      customFileName:
        description: 'Enter a custome name for the built APK'
        type: string
        default: 'TestApp'
      buildPlatformAndroid:
        description: 'Build to Android?'
        type: boolean
        required: true
        default: false
      buildPlatformIOS:
        description: 'Build to IOS?'
        type: boolean
        required: true
        default: false

      

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        buildPlatform: [Android, iOS]
      
    defaults:
      run:
        working-directory: ./cli
          
    steps:
          

      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Input validation
        run: |
          if [[ "${{ github.event.inputs.buildPlatformAndroid }}" == "false" && "${{ github.event.inputs.buildPlatformIOS }}" == "false" ]]; then
            echo "Must select a build platform"
            exit 1
          fi
          if [[ "${{ github.event.inputs.customFileName }}" == "" ]]; then
            echo "Must have a file name"
            exit 1
          fi
          if [[ "${{ matrix.buildPlatform }}" == "Android" && "${{ github.event.inputs.buildPlatformAndroid }}" != "true" ]] || [[ "${{ matrix.buildPlatform }}" == "iOS" && "${{ github.event.inputs.buildPlatformIOS }}" != "true" ]]; then
            echo "Skipping ${{ matrix.buildPlatform }} build"
            exit 1
          fi

      - name: Make file executable
        run:  chmod +x build.sh upload.sh
      
      - name: Version tagging
        if: github.ref == 'refs/heads/main'
        id: auto_version
        uses: anothrNick/github-tag-action@1.67.0
        with:
          CUSTOM_TAG: "v${{ github.run_number }}-${{ matrix.buildPlatform }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
      
      - name: Start timer
        id: timer_start
        run: echo "start=$(date +%s)" >> $GITHUB_OUTPUT

      # CLI call to simulated build process
      - name: Run Build
        run: |
          Version="${{ steps.auto_version.outputs.new_tag || 'dev' }}"
          ./build.sh --platform "${{ matrix.buildPlatform }}" --project-name "${{github.event.inputs.customFileName}}" --profile --version "$Version"

      - name: Stop timer
        id: timer_end
        run: |
          end=$(date +%s)
          duration=$((end - ${{ steps.timer_start.outputs.start }}))
          echo "Build for "${{ matrix.buildPlatform }}" took ${duration} seconds"
      
      - name: Upload profiling artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-profiles for "${{ matrix.buildPlatform }}"
          path: cli/build/"${{ matrix.buildPlatform }}"/*.pro

      # CLI call to simulated upload process
          
      - name: Upload
        if: github.ref == 'refs/heads/main'
        run: |
          UploadPlatform=$(echo "${{ matrix.buildPlatform }}" | tr '[:upper:]' '[:lower:]')

          if [[ "${{ matrix.buildPlatform }}" == "iOS" ]]; then
            UPLOAD_DIR="build/iOS/Assets"
          else
            UPLOAD_DIR="build/Android"
          fi

          for file in build/${{ matrix.buildPlatform }}/*; do
            ./upload.sh $UploadPlatform "$file"
          done
